"""mig2 - test

Revision ID: 9e81d52975e7
Revises: 20dfb8d6ebc0
Create Date: 2025-09-01 16:09:37.429528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
# вторая миграция
revision: str = '9e81d52975e7'
down_revision: Union[str, Sequence[str], None] = '20dfb8d6ebc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
